[[aws_checksums]]
arch = "aarch64"
git-tree-sha1 = "a23d6f0176736c9ab4d01a3d374d4e0a8ce0874b"
os = "macos"

    [[aws_checksums.download]]
    sha256 = "887787c00b0b0d847cd3b63fdcffa7df08707842b4e8878e9f0f309c6647bb36"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v0.2.3+0/aws_checksums.v0.2.3.aarch64-apple-darwin.tar.gz"
[[aws_checksums]]
arch = "aarch64"
git-tree-sha1 = "f3908acf3b2a761b3bd5ea94da13a86ec2c15215"
libc = "glibc"
os = "linux"

    [[aws_checksums.download]]
    sha256 = "2361a573edc149915fa228069a91eaf3daf5924e8420667ffa1bc61408bb70e4"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v0.2.3+0/aws_checksums.v0.2.3.aarch64-linux-gnu.tar.gz"
[[aws_checksums]]
arch = "aarch64"
git-tree-sha1 = "8d9bc7facded4afe91ee163107b787d05a56e04a"
libc = "musl"
os = "linux"

    [[aws_checksums.download]]
    sha256 = "a256450ea60d2583c5aa4b3b5265623e1935184dcb05cf30a8116df27ce0347f"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v0.2.3+0/aws_checksums.v0.2.3.aarch64-linux-musl.tar.gz"
[[aws_checksums]]
arch = "aarch64"
git-tree-sha1 = "cb23f08f57da59f971b8b94941cf8fa7dc7bb389"
os = "freebsd"

    [[aws_checksums.download]]
    sha256 = "5ab2530eb89789455b0f727c44245e843601acbe299dbdb0dfb6be72b86335ff"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v0.2.3+0/aws_checksums.v0.2.3.aarch64-unknown-freebsd.tar.gz"
[[aws_checksums]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6c5f62c7344a20effcef82eebf3cd8e056997619"
libc = "glibc"
os = "linux"

    [[aws_checksums.download]]
    sha256 = "3466e4f7fb396cf885a4d5d010e5db045c472be123f0faf509a963b5ebdc070f"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v0.2.3+0/aws_checksums.v0.2.3.armv6l-linux-gnueabihf.tar.gz"
[[aws_checksums]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2363764790cc6ae5d8232327defb1c6114f1f4ff"
libc = "musl"
os = "linux"

    [[aws_checksums.download]]
    sha256 = "dfd3dc07484cc8e56ee09b5e5706e86585f76bbc373bec0893d63306f28451f4"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v0.2.3+0/aws_checksums.v0.2.3.armv6l-linux-musleabihf.tar.gz"
[[aws_checksums]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6c5f62c7344a20effcef82eebf3cd8e056997619"
libc = "glibc"
os = "linux"

    [[aws_checksums.download]]
    sha256 = "3466e4f7fb396cf885a4d5d010e5db045c472be123f0faf509a963b5ebdc070f"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v0.2.3+0/aws_checksums.v0.2.3.armv7l-linux-gnueabihf.tar.gz"
[[aws_checksums]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2363764790cc6ae5d8232327defb1c6114f1f4ff"
libc = "musl"
os = "linux"

    [[aws_checksums.download]]
    sha256 = "dfd3dc07484cc8e56ee09b5e5706e86585f76bbc373bec0893d63306f28451f4"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v0.2.3+0/aws_checksums.v0.2.3.armv7l-linux-musleabihf.tar.gz"
[[aws_checksums]]
arch = "i686"
git-tree-sha1 = "ee5470823005482723bf772a3d3202653619665f"
libc = "glibc"
os = "linux"

    [[aws_checksums.download]]
    sha256 = "a118cdaa75b63cbebde84173729c87d287d8b11f61dd3c8b17c65e809ea1d14d"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v0.2.3+0/aws_checksums.v0.2.3.i686-linux-gnu.tar.gz"
[[aws_checksums]]
arch = "i686"
git-tree-sha1 = "27e462a52461efc32717d02bb186632b3d17afb6"
libc = "musl"
os = "linux"

    [[aws_checksums.download]]
    sha256 = "b0b9d4b729f782741e873b54e966f0ab6cec3a840d6852e99161e65592a101a2"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v0.2.3+0/aws_checksums.v0.2.3.i686-linux-musl.tar.gz"
[[aws_checksums]]
arch = "powerpc64le"
git-tree-sha1 = "b94f6ff1c533766404e87e881e29cf1b9d9254bc"
libc = "glibc"
os = "linux"

    [[aws_checksums.download]]
    sha256 = "38fe50bfce40fcf8844e0598c1ef7d84224294816e8adc3d9f921d4dbdfb9024"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v0.2.3+0/aws_checksums.v0.2.3.powerpc64le-linux-gnu.tar.gz"
[[aws_checksums]]
arch = "riscv64"
git-tree-sha1 = "159f45f0c24fd86702c4718564bc75830a248e3d"
libc = "glibc"
os = "linux"

    [[aws_checksums.download]]
    sha256 = "1d228edcc6c094713744957384b1178c6fb5eafe13f789e913830d6986b12194"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v0.2.3+0/aws_checksums.v0.2.3.riscv64-linux-gnu.tar.gz"
[[aws_checksums]]
arch = "x86_64"
git-tree-sha1 = "f7c8dfd9192e5d4d652bc7ea714cfb985a81a7f5"
os = "macos"

    [[aws_checksums.download]]
    sha256 = "e40cb47ffeb565dac3136bb9cdb4e6c0a6488f1dc65072c8c4c5b6dbed0392bb"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v0.2.3+0/aws_checksums.v0.2.3.x86_64-apple-darwin.tar.gz"
[[aws_checksums]]
arch = "x86_64"
git-tree-sha1 = "07f769b25a4f00040eea62c596c6be857f320a68"
libc = "glibc"
os = "linux"

    [[aws_checksums.download]]
    sha256 = "ef1e1c9fd0ee4da811f9c2bf04590c01f2807be1af3a76a955a5ad88c6f23a34"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v0.2.3+0/aws_checksums.v0.2.3.x86_64-linux-gnu.tar.gz"
[[aws_checksums]]
arch = "x86_64"
git-tree-sha1 = "e6519fab5fcf84c81b3e8615194fc511b6ac87d9"
libc = "musl"
os = "linux"

    [[aws_checksums.download]]
    sha256 = "3ef4c61a22c8f401acf157edaf80f979b56b215d1b13b94f2d37808394369cce"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v0.2.3+0/aws_checksums.v0.2.3.x86_64-linux-musl.tar.gz"
[[aws_checksums]]
arch = "x86_64"
git-tree-sha1 = "f6e75d406285bc7ed7d61867d8045af1a076b90f"
os = "freebsd"

    [[aws_checksums.download]]
    sha256 = "0f6b9651948f43069e338b887b9cb70d6b438b38e75249916247fb8e5fbce1ee"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v0.2.3+0/aws_checksums.v0.2.3.x86_64-unknown-freebsd.tar.gz"
[[aws_checksums]]
arch = "x86_64"
git-tree-sha1 = "e2a3311e24f1f6953aa41e599ad07eea994698bd"
os = "windows"

    [[aws_checksums.download]]
    sha256 = "6e69208ea5a4c2332d9aef8e8017280fa423c6d86241df31b4956b745d0d74c6"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v0.2.3+0/aws_checksums.v0.2.3.x86_64-w64-mingw32.tar.gz"
