[[aws_checksums]]
arch = "aarch64"
git-tree-sha1 = "c6dee4cb3dbd7d2c03af87182dbbd60887209f45"
os = "macos"

    [[aws_checksums.download]]
    sha256 = "bf47e8e78677d16cea05f35e306d38912125743649697c4d4e9519dd8269a5b5"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v1.0.0+0/aws_checksums.v1.0.0.aarch64-apple-darwin.tar.gz"
[[aws_checksums]]
arch = "aarch64"
git-tree-sha1 = "4ca79a3c2983d924f576f33a66bdf3d1046df3c6"
libc = "glibc"
os = "linux"

    [[aws_checksums.download]]
    sha256 = "bd524fa95c272c242c808e51231967e21a349e0928dbcc475cf3a0b74a1e0f99"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v1.0.0+0/aws_checksums.v1.0.0.aarch64-linux-gnu.tar.gz"
[[aws_checksums]]
arch = "aarch64"
git-tree-sha1 = "f099468f3196a86949b19d94114913d8f37fa901"
libc = "musl"
os = "linux"

    [[aws_checksums.download]]
    sha256 = "bf52d1e5ded0084db50893c987b2a4ac37ba2f2285706530fb58118d0184eec5"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v1.0.0+0/aws_checksums.v1.0.0.aarch64-linux-musl.tar.gz"
[[aws_checksums]]
arch = "aarch64"
git-tree-sha1 = "8fc9a2e7b8fd411814e85093c49535bf4b7b63e1"
os = "freebsd"

    [[aws_checksums.download]]
    sha256 = "129a8381889026b89a4db508f57441753493dcfe2eccbd8fbee53da6a9bb7211"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v1.0.0+0/aws_checksums.v1.0.0.aarch64-unknown-freebsd.tar.gz"
[[aws_checksums]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "309c5d76a0099bf4c18a8a0c23e5e1bb7e6da690"
libc = "glibc"
os = "linux"

    [[aws_checksums.download]]
    sha256 = "498b307dd1f87954816e40e4d829b428fb5f63600a52610823d97f67dff34af9"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v1.0.0+0/aws_checksums.v1.0.0.armv6l-linux-gnueabihf.tar.gz"
[[aws_checksums]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "09641486e95386f10c5a46abb26939d839aca735"
libc = "musl"
os = "linux"

    [[aws_checksums.download]]
    sha256 = "b3b59347095ece126bac2a8bae82bc5db30af5df3a5e30fbe08862381f85bf05"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v1.0.0+0/aws_checksums.v1.0.0.armv6l-linux-musleabihf.tar.gz"
[[aws_checksums]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "309c5d76a0099bf4c18a8a0c23e5e1bb7e6da690"
libc = "glibc"
os = "linux"

    [[aws_checksums.download]]
    sha256 = "498b307dd1f87954816e40e4d829b428fb5f63600a52610823d97f67dff34af9"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v1.0.0+0/aws_checksums.v1.0.0.armv7l-linux-gnueabihf.tar.gz"
[[aws_checksums]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "09641486e95386f10c5a46abb26939d839aca735"
libc = "musl"
os = "linux"

    [[aws_checksums.download]]
    sha256 = "b3b59347095ece126bac2a8bae82bc5db30af5df3a5e30fbe08862381f85bf05"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v1.0.0+0/aws_checksums.v1.0.0.armv7l-linux-musleabihf.tar.gz"
[[aws_checksums]]
arch = "i686"
git-tree-sha1 = "67b58dfa9cc182a44077d7a88cbe2ae58522bba9"
libc = "glibc"
os = "linux"

    [[aws_checksums.download]]
    sha256 = "6b029258081e3ab0ef8089eb32a23798b69982a50930bba404c234a34e3302a3"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v1.0.0+0/aws_checksums.v1.0.0.i686-linux-gnu.tar.gz"
[[aws_checksums]]
arch = "i686"
git-tree-sha1 = "0d5d262647a41364b1e6d8c00dd02db956c51eb3"
libc = "musl"
os = "linux"

    [[aws_checksums.download]]
    sha256 = "5dabf8c54baffd75ae26d486e04f8bc3abf262a4c4c92745368702efa5c7cc89"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v1.0.0+0/aws_checksums.v1.0.0.i686-linux-musl.tar.gz"
[[aws_checksums]]
arch = "powerpc64le"
git-tree-sha1 = "fad764a095a8e643f9f045b4d5a8693d41f7f5eb"
libc = "glibc"
os = "linux"

    [[aws_checksums.download]]
    sha256 = "136ead4f21964c43b2318c93155d73f32297ff1f657b1d983d3f9ab39d693ff2"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v1.0.0+0/aws_checksums.v1.0.0.powerpc64le-linux-gnu.tar.gz"
[[aws_checksums]]
arch = "riscv64"
git-tree-sha1 = "53647e3903f23ccb90abe429c945c09518260ac2"
libc = "glibc"
os = "linux"

    [[aws_checksums.download]]
    sha256 = "60ff56064ff748d5e65d19e5d56d22316fa1df94b2c1930c69e6c9ddfbff3e96"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v1.0.0+0/aws_checksums.v1.0.0.riscv64-linux-gnu.tar.gz"
[[aws_checksums]]
arch = "x86_64"
git-tree-sha1 = "35b19f89ef01b5de1ae6285bb517b9c5a22f8b3b"
os = "macos"

    [[aws_checksums.download]]
    sha256 = "ad368f463f6562c6c4bcd2b96ad25d6e0f5a76b086d053134945bd9ca0fda0c9"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v1.0.0+0/aws_checksums.v1.0.0.x86_64-apple-darwin.tar.gz"
[[aws_checksums]]
arch = "x86_64"
git-tree-sha1 = "7435fbb2a705d83682a1857fec7bdc2f41839f59"
libc = "glibc"
os = "linux"

    [[aws_checksums.download]]
    sha256 = "46600f279ca85758f1a2d61ac106e2a288011fb4f7ce5574bc1104d2bfb06d52"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v1.0.0+0/aws_checksums.v1.0.0.x86_64-linux-gnu.tar.gz"
[[aws_checksums]]
arch = "x86_64"
git-tree-sha1 = "ba12f0d6e8db474833f9ba4dc675ab9f82103fb9"
libc = "musl"
os = "linux"

    [[aws_checksums.download]]
    sha256 = "387cf389fb21b1992c37a6d1338e28b0c51de5a3a423501ce63d6429f388729c"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v1.0.0+0/aws_checksums.v1.0.0.x86_64-linux-musl.tar.gz"
[[aws_checksums]]
arch = "x86_64"
git-tree-sha1 = "3cbaa298e09423220d040ef0d3d15b6ccf974452"
os = "freebsd"

    [[aws_checksums.download]]
    sha256 = "d80b700749b2adaf8826efda46c9df951e5d86e1384cec4e8b8259fca18ad758"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v1.0.0+0/aws_checksums.v1.0.0.x86_64-unknown-freebsd.tar.gz"
[[aws_checksums]]
arch = "x86_64"
git-tree-sha1 = "5ef7eb302912192ca1c33d5e5487f3df0a6a15f7"
os = "windows"

    [[aws_checksums.download]]
    sha256 = "c5f950b6511532d89f422da827bf57914ba217b868d020bb7401e697682af4c5"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v1.0.0+0/aws_checksums.v1.0.0.x86_64-w64-mingw32.tar.gz"
