[[aws_checksums]]
arch = "aarch64"
git-tree-sha1 = "21f5481723c3778ec122f41b19ae078004c43b03"
os = "macos"

    [[aws_checksums.download]]
    sha256 = "dbceb200aaafbfea7c0c9dcd9ba2a8cfa719bac12414d2372dcb7f3880e07d22"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v0.2.5+0/aws_checksums.v0.2.5.aarch64-apple-darwin.tar.gz"
[[aws_checksums]]
arch = "aarch64"
git-tree-sha1 = "b05d2e82f21853c06ad531a66bc1a36f1b68d134"
libc = "glibc"
os = "linux"

    [[aws_checksums.download]]
    sha256 = "43a19e17cdd410ead7df3480c003f347cf4638483d01722172fd38cc99846c6e"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v0.2.5+0/aws_checksums.v0.2.5.aarch64-linux-gnu.tar.gz"
[[aws_checksums]]
arch = "aarch64"
git-tree-sha1 = "681b17c76e3784915a2362208fc7dfb59efaddc5"
libc = "musl"
os = "linux"

    [[aws_checksums.download]]
    sha256 = "678c981a5c70396fe92b535afd3f719d1613c829a57ad200f81cec585f68a6f1"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v0.2.5+0/aws_checksums.v0.2.5.aarch64-linux-musl.tar.gz"
[[aws_checksums]]
arch = "aarch64"
git-tree-sha1 = "ed8d22b2bd40cea7de029d13bb8dae1266779479"
os = "freebsd"

    [[aws_checksums.download]]
    sha256 = "57934d463a69cddd9a16545d00a049901513c15e33a0442c1d1d9da3e60775af"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v0.2.5+0/aws_checksums.v0.2.5.aarch64-unknown-freebsd.tar.gz"
[[aws_checksums]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "88479c692da6e23ba91847826e2e7563740cd50c"
libc = "glibc"
os = "linux"

    [[aws_checksums.download]]
    sha256 = "4525f68a84cb3c41f3c952733b1871073086fe1072e7a49d4bb92be52a46b6d6"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v0.2.5+0/aws_checksums.v0.2.5.armv6l-linux-gnueabihf.tar.gz"
[[aws_checksums]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "04e3ba2a412ad6c8a9853cebe735d1445c67774f"
libc = "musl"
os = "linux"

    [[aws_checksums.download]]
    sha256 = "bd43c8bdb78298e6b91455cba5c07bdac918f1ef07d4e57aab0fbc87c28f54e7"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v0.2.5+0/aws_checksums.v0.2.5.armv6l-linux-musleabihf.tar.gz"
[[aws_checksums]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "88479c692da6e23ba91847826e2e7563740cd50c"
libc = "glibc"
os = "linux"

    [[aws_checksums.download]]
    sha256 = "4525f68a84cb3c41f3c952733b1871073086fe1072e7a49d4bb92be52a46b6d6"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v0.2.5+0/aws_checksums.v0.2.5.armv7l-linux-gnueabihf.tar.gz"
[[aws_checksums]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "04e3ba2a412ad6c8a9853cebe735d1445c67774f"
libc = "musl"
os = "linux"

    [[aws_checksums.download]]
    sha256 = "bd43c8bdb78298e6b91455cba5c07bdac918f1ef07d4e57aab0fbc87c28f54e7"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v0.2.5+0/aws_checksums.v0.2.5.armv7l-linux-musleabihf.tar.gz"
[[aws_checksums]]
arch = "i686"
git-tree-sha1 = "e445ce647390289fe320ecd36a92fad02f076cb8"
libc = "glibc"
os = "linux"

    [[aws_checksums.download]]
    sha256 = "732f1250d1ebaaa672619612e3bd2a15b28fb11b9ff8fee1549680b9e312969c"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v0.2.5+0/aws_checksums.v0.2.5.i686-linux-gnu.tar.gz"
[[aws_checksums]]
arch = "i686"
git-tree-sha1 = "fdb50bf6dd9c427a57a0b3b277564f9a262ae8cf"
libc = "musl"
os = "linux"

    [[aws_checksums.download]]
    sha256 = "d0836546391f033afc4bd84859798ba526cf902ce598e3ae25c0f797849470d4"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v0.2.5+0/aws_checksums.v0.2.5.i686-linux-musl.tar.gz"
[[aws_checksums]]
arch = "powerpc64le"
git-tree-sha1 = "1e4c428ec503e697de7e7664e86071de25237377"
libc = "glibc"
os = "linux"

    [[aws_checksums.download]]
    sha256 = "9adcb1329ef675b8dc248beb931db7636336c0cfa44b0ca50cbb704beec62c72"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v0.2.5+0/aws_checksums.v0.2.5.powerpc64le-linux-gnu.tar.gz"
[[aws_checksums]]
arch = "riscv64"
git-tree-sha1 = "965d84e20e1ab4f01192fd1b7c046247cc80cfca"
libc = "glibc"
os = "linux"

    [[aws_checksums.download]]
    sha256 = "4352815cd1d51a7aaa14c692eec3d9417e2abb5c8c5c9e5290bdebef5f93b57b"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v0.2.5+0/aws_checksums.v0.2.5.riscv64-linux-gnu.tar.gz"
[[aws_checksums]]
arch = "x86_64"
git-tree-sha1 = "13d405414fd74ba2bc4395d705e77f4d05bda2f6"
os = "macos"

    [[aws_checksums.download]]
    sha256 = "e5779d3d15fa8c06feb701bc94f03781ec176778ae5079beb84692fe9ed73951"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v0.2.5+0/aws_checksums.v0.2.5.x86_64-apple-darwin.tar.gz"
[[aws_checksums]]
arch = "x86_64"
git-tree-sha1 = "2f8baf8f1716ab06946200e72e2c99cea8a728c4"
libc = "glibc"
os = "linux"

    [[aws_checksums.download]]
    sha256 = "6ff6ee7636a3f5748a39a2f49a03f88b21b5859b4c5473c451736644af402f46"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v0.2.5+0/aws_checksums.v0.2.5.x86_64-linux-gnu.tar.gz"
[[aws_checksums]]
arch = "x86_64"
git-tree-sha1 = "69ad0294fa557edb9ac23d4c468588ddc8d532ae"
libc = "musl"
os = "linux"

    [[aws_checksums.download]]
    sha256 = "dca4e535a520b422f17eeea92cfe5acaeb4cab93f540d8ca7100f77c0ecae3ec"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v0.2.5+0/aws_checksums.v0.2.5.x86_64-linux-musl.tar.gz"
[[aws_checksums]]
arch = "x86_64"
git-tree-sha1 = "72760c69ed9c8e4eba652bd4f39ca730dff57338"
os = "freebsd"

    [[aws_checksums.download]]
    sha256 = "d53dee6fe4bd3bb7e4084964c8770c078e4fbc78512811d1dea09d18f635a8ef"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v0.2.5+0/aws_checksums.v0.2.5.x86_64-unknown-freebsd.tar.gz"
[[aws_checksums]]
arch = "x86_64"
git-tree-sha1 = "83fbec2a7e2b7a04267848bccb309cb879c844fe"
os = "windows"

    [[aws_checksums.download]]
    sha256 = "c618769004af6682e1478fa49677916c43ac38d560710e6742dd31557e41b554"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v0.2.5+0/aws_checksums.v0.2.5.x86_64-w64-mingw32.tar.gz"
