[[aws_checksums]]
arch = "aarch64"
git-tree-sha1 = "e3940bacfa4dbb3696931892e2b791ea55629760"
os = "macos"

    [[aws_checksums.download]]
    sha256 = "da54de36ab7ff67d4c98dc5b76e26f266f39177b49532dbcf22d04fe45fae073"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v0.2.9+0/aws_checksums.v0.2.9.aarch64-apple-darwin.tar.gz"
[[aws_checksums]]
arch = "aarch64"
git-tree-sha1 = "721cc954af9f5e30b4077804776d86c5eac19938"
libc = "glibc"
os = "linux"

    [[aws_checksums.download]]
    sha256 = "ce4f6b1a87cda55dc6b69122d69b6f90db8439a4314f727ebbe6825e498a6992"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v0.2.9+0/aws_checksums.v0.2.9.aarch64-linux-gnu.tar.gz"
[[aws_checksums]]
arch = "aarch64"
git-tree-sha1 = "5fa82866590a8bc82d1a4374465a0e686291e109"
libc = "musl"
os = "linux"

    [[aws_checksums.download]]
    sha256 = "0bc2e17ba72411569590f8f420a5cb367c66d8f041a97186a9d418954ee5cdfc"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v0.2.9+0/aws_checksums.v0.2.9.aarch64-linux-musl.tar.gz"
[[aws_checksums]]
arch = "aarch64"
git-tree-sha1 = "542531bc12cf4a14223ba12a787b6a31bcf02da9"
os = "freebsd"

    [[aws_checksums.download]]
    sha256 = "f7e44d01a590df4e78edf89191db8fcf2e9781cece2f1e1ae6c1167753cb6460"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v0.2.9+0/aws_checksums.v0.2.9.aarch64-unknown-freebsd.tar.gz"
[[aws_checksums]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "63f892788db03b7d977c9793c9c3f5e26be6e20e"
libc = "glibc"
os = "linux"

    [[aws_checksums.download]]
    sha256 = "510d402943555637609979706d3865bec0830afe9cbef04e413a663e1d836b91"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v0.2.9+0/aws_checksums.v0.2.9.armv6l-linux-gnueabihf.tar.gz"
[[aws_checksums]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "12515f8a46e5d9497d34f3adeb29139967b4695e"
libc = "musl"
os = "linux"

    [[aws_checksums.download]]
    sha256 = "450960690b60adbeb6b45b7929c53a41714dd65f732352dc0ea700e909cccce6"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v0.2.9+0/aws_checksums.v0.2.9.armv6l-linux-musleabihf.tar.gz"
[[aws_checksums]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "63f892788db03b7d977c9793c9c3f5e26be6e20e"
libc = "glibc"
os = "linux"

    [[aws_checksums.download]]
    sha256 = "510d402943555637609979706d3865bec0830afe9cbef04e413a663e1d836b91"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v0.2.9+0/aws_checksums.v0.2.9.armv7l-linux-gnueabihf.tar.gz"
[[aws_checksums]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "12515f8a46e5d9497d34f3adeb29139967b4695e"
libc = "musl"
os = "linux"

    [[aws_checksums.download]]
    sha256 = "450960690b60adbeb6b45b7929c53a41714dd65f732352dc0ea700e909cccce6"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v0.2.9+0/aws_checksums.v0.2.9.armv7l-linux-musleabihf.tar.gz"
[[aws_checksums]]
arch = "i686"
git-tree-sha1 = "9c86f4c481982959b7c4338206133d299d0e0c3a"
libc = "glibc"
os = "linux"

    [[aws_checksums.download]]
    sha256 = "2b6ffdfea222f983f8cecae37451d91840d86d247f0d7501ac815b19b43fdd92"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v0.2.9+0/aws_checksums.v0.2.9.i686-linux-gnu.tar.gz"
[[aws_checksums]]
arch = "i686"
git-tree-sha1 = "4dc8158a5d90e2f349bd930f80cec657f16ffdf6"
libc = "musl"
os = "linux"

    [[aws_checksums.download]]
    sha256 = "707a98d9130f8170dc45720a854786db4fd23300631d7778289c1114b148eae4"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v0.2.9+0/aws_checksums.v0.2.9.i686-linux-musl.tar.gz"
[[aws_checksums]]
arch = "powerpc64le"
git-tree-sha1 = "f8fc802e4a8bb318abcc0cdfc2c2941eecd5d7e6"
libc = "glibc"
os = "linux"

    [[aws_checksums.download]]
    sha256 = "593f06ce7db37b56eea7dbd7f88c6beee96e6fa6aba51928ce8324d2841ab59d"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v0.2.9+0/aws_checksums.v0.2.9.powerpc64le-linux-gnu.tar.gz"
[[aws_checksums]]
arch = "riscv64"
git-tree-sha1 = "31d281dd8aa1e34e9415a2ecbf63746da1a0c0f9"
libc = "glibc"
os = "linux"

    [[aws_checksums.download]]
    sha256 = "8d4896048587d218f4736cd2059b52ed8cc6baa4eb879a72bb8e77f0695834ab"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v0.2.9+0/aws_checksums.v0.2.9.riscv64-linux-gnu.tar.gz"
[[aws_checksums]]
arch = "x86_64"
git-tree-sha1 = "3ca6e0faf3f12afe3eabee4bc3ef792b283b51f7"
os = "macos"

    [[aws_checksums.download]]
    sha256 = "ef6019ee39ffb1d94721ac9e0da8b980550fdeb358391393cb2fc6b5097f62ce"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v0.2.9+0/aws_checksums.v0.2.9.x86_64-apple-darwin.tar.gz"
[[aws_checksums]]
arch = "x86_64"
git-tree-sha1 = "7b0103588fbd6546c1dfb0c749dc89447883b916"
libc = "glibc"
os = "linux"

    [[aws_checksums.download]]
    sha256 = "886dc82730beda35b6b3b6305fdf3c2fa5b825fb91259fece271d6e44927448c"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v0.2.9+0/aws_checksums.v0.2.9.x86_64-linux-gnu.tar.gz"
[[aws_checksums]]
arch = "x86_64"
git-tree-sha1 = "bd7ef4228158291a564fc59ee4b187bf38dbaf32"
libc = "musl"
os = "linux"

    [[aws_checksums.download]]
    sha256 = "26e3015a35acef0bd018ee4bb578996ffaf1b9780a8e21d55e86d6b7c7406032"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v0.2.9+0/aws_checksums.v0.2.9.x86_64-linux-musl.tar.gz"
[[aws_checksums]]
arch = "x86_64"
git-tree-sha1 = "37e6da39fecab199c4d3f7fff3ffbf62f737f736"
os = "freebsd"

    [[aws_checksums.download]]
    sha256 = "af4a7d93f2ebb6b4f9755528d853e83bd4e182f83e9fd247a5685b9425889e08"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v0.2.9+0/aws_checksums.v0.2.9.x86_64-unknown-freebsd.tar.gz"
[[aws_checksums]]
arch = "x86_64"
git-tree-sha1 = "54db48b075f92a6d9cf267634e1417229d9809f1"
os = "windows"

    [[aws_checksums.download]]
    sha256 = "389b17780de75e8be2351886c49f71a7d1212414ca2bc3c15831d3a674edfc4b"
    url = "https://github.com/JuliaBinaryWrappers/aws_checksums_jll.jl/releases/download/aws_checksums-v0.2.9+0/aws_checksums.v0.2.9.x86_64-w64-mingw32.tar.gz"
